server:
  port: 1234 #\u9879\u76EE\u542F\u52A8\u8BBF\u95EE\u7AEF\u53E3
spring:
  application:
    name: goods
  datasource: #\u8FDE\u63A5\u6570\u636E\u5E93\u914D\u7F6E
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/approving?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  servlet:
  multipart: #\u6587\u4EF6\u4E0A\u4F20\u914D\u7F6E
    max-file-size: 10MB
    max-request-size: 50MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.approving.system.domain
